#!/bin/sh
if [ -d /usr/lib/python2.6 ]; then
if [ ! -d /usr/lib/python2.7 ]; then
echo "**********************************************************"
echo "*                        Oooooooops                      *"
echo "*                Not Compatible with (OE1.6)             *"
echo "**********************************************************"
sleep 2
exit 1 
fi
fi
echo "Checking for an older version in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/PluginsPanel ]
then 
echo "PluginsPanel Installato"
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/PluginsPanel > /dev/null 2>&1
echo "Una versione precedente trovata e rimossa..."
else
echo "Nessun PluginsPanel Installato"
echo "***********************************"
echo "* Proceeding to installation...   *"
echo "***********************************"
fi
